### ISSUE TITLE
Suggestion: Role presets

### ISSUE THREAD

**Issue by Billology** [Haplo064/PixelPerfect#10]
I'd like to suggest role/job presets as a feature. 

Even just a basic "if role healer, then outer ring on" / "if role dps, then outer ring off" would be much appreciated.

**Comment by thoccavelli** [comment]
Agree totally...please please consider adding individual job presets.

I play BLM and SGE.  BLM uses 25 yalm radius for spells, where as SGE uses 15 yalm radius. 

Would be awesome if the plugin automatically switched the settings when you switch jobs. 

Btw, this plugin makes SGE quality of life so much better since it's easy to eyeball party members who are within healing radius.  Thank you!!!

**Comment by Haplo064** [comment]
Added.
