### ISSUE TITLE
Request for a 2nd Outer Ring

### ISSUE THREAD

**Issue by iwantcookiesnow** [Haplo064/PixelPerfect#2]
Hello,

I'd love to have a second outer ring displayed on my character so I could set both of them to different ranges!
I'm playing dancer and am using your plugin to help with judging the range of my aoe skills. For that, I'm frequently switching the radius of the ring between 5y (melee aoe range) for some fights and 25y (dance range) for other content. Seeing both at the same time and possibly in different colors would be a huge plus for me.

Thank you for reading and I appreciate the effort you put into this plugin! :)

**Comment by Deejnis** [comment]
I'd like to add on that that there should be a "/pp ring #" command so you can create your own ring on the fly. 
This way you can also insert the command into a classjob change macro so that you can have a different ring for each class.

A "/pp ring 0" command would disable the ring when changing to a class that doesn't need it.

**Comment by DJFarr** [comment]
Yes I'd love the ability to add to a list of rings, rather than just have the 1.
Having a series of rings at different ranges and colours would be very helpful

**Comment by Haplo064** [comment]
Added this and so much more
